title: Entangled Threats
description: Cybersecurity, Web Dev & Quantum Security Portfolio
theme: just-the-docs
url: "https://entangledthreats.com"
baseurl: "" # root
color_scheme: dark

# Optional: order or hide pages
nav_sort: true
